language: common-lisp
sudo: required

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s prove -e '(or (prove:run :travis-test-test) (uiop:quit -1))'

env:
    global:
        - secure: "hw3eofv6Wh6DrMuCr93THw4uUa4wwnw3QoJ71dnLe8BjkMgdAZRVCdRfm3BAq27RSFRnQms5pzjh4+qUwcu4gRw0c5OZkuRbCOBOBmgiHmBQKak4Pl0NmBIkBSyMTlr47zXDhkD5ZMUAMRlU8Qg3nm0B2KA//GsF2HEenFyLu6MjrJwS7NyMQF48t72vmZtOKxuKWjiFfIrlrAUstgDkLxeX71JxL0WI4t4tyCdu2qA+Rs53mh+2egSuv7KuK/LnlV4ZeV6OAEDz+vOYzheOxjhc3sJGp1c4CBo5GpqCtGM/6cJ5WEWMT7vnKa8SsaWnBQDUKLraIBtR6+1jluzOHzJ2Kz3DjcfOZuftYV/eiag0cNQdU1zWhbxafVtX4R5BL5uvPHfFFvC8+VtZom0AoFwNR4ssTYPlJLS5D+o4A64k3FnMAV+REGpToK+wHpPulVUWvmOSdfHteEpGBGQo+uLE1Aqnt+NKsHxkW4vOEudC0X2lC/fHzbJ+EsE7O3YkBu3VHd+HqAWEhEgd1k8qSXDZFAT5BMsdyBuZ1UUi3xtUxImeSmMDeyrNuSPVlN57kjnHS/8CXP55bbKsoKLTN2h/tZArCSY5lhwADSD9zgN/gsu5W+oaoVCzH0gXwVMInUc6fTiuuE1qXcx+2lON+yLde5ZWEah4tGvGCxG0kfc="
        - secure: "rzbkd87TtCMihjMuz1dg95LRe3Vbh+LCPGYyvKjdq+0OBX1DNR1kuUWA/vcclJn0SHrV5EtJcpC4Jwp2Ic1i6bHu6n4d/R8SaB+vhA3vTOh01BMMY9SADdO7z0dUXrpmWU0LEdDEGqmgYCxsV99Sp5Cm17XDeQQAjr4NQQfjfBsXubTE8rAeudRsjAwbSJ4WaPvG00O2YG636880XNIFfx41NHPvDiEKRRlPgT+Dv1nka4IGtwJLPCNrUzJK2cIDexqVFksh+azwQPG4u/iSAuES12/x6Prtfha95XBWGPPr6KNZZeZz/etXgQGDEYLe07ud+AzsgxNw4JURw4NR7PnJVUdSANSAb/FmR+fwGRgo+02zq1wJ3DEIuowwGXPCkT7yCal4aIMCvpKUUSUfQZFFagv0wS++f2AH+grdm2Pl7edVOx/W9Zmmsvy1ATPAYmdGOZH48W6PTJtgHTsIr1vFINJztIOY8/746kHlQEO5pOi8Z3aJjSPjbr9MIQxE/9kBUUtK/WAtDcmmQg/xV2OgWwInpX0aO+ETQnVLn15cy+Q58i+z7Q2607d5BqiHP9oUy2rPYJDkuLMU1CYAH5ehJJj0iAn2HdtjDuRTa8SPQLuk34zDwN07Nmz9tEEsnD0YcfzXdk8sHx7BEOnOnNhC6XMUG+mxxrQLgq+PErg="
        - secure: "HMVoY16GB7b7w+0m8OvjPgKTAEuU1YOcDt4Et0oWopN8aVxVSEgtmcYVRbSx7Q8U2BsNNi9/9jAR/47JqmriAqqHmNQ3fXnaUwEQU3yTaXdnJvMM6EcEQ/cNPbrKRv7j0L5diGkKFG87S2EHhK7OunsNi5g+riAHnU5MVcHhFZvAXww7iL2qRcQ8FPrHvpI8IR0G0hzQUqfNb3PlDKyAMDqTshSCQLDizBI5XzkCYGbq8bHNEqYt6blz6pcWU2qYAkZMhycLIrjHxdjRFY21uoN9rOKMojxsbY0jpLkoGhuQ0bZ7TmPp+Tf53yak3uwsdAP2unby5O5f5NiivE3JyYva7crB2dphETsvDF+lGUip4J1GXJb+Ou2VLjsYoj9zrHY+bfMJE3pFF/1yIlVmG7PDkI5RrNUAC8CfLXzEFO+qF8Wn88seM0J/N62RV1nxSlobV1Br/YKZSXSaa6OEC7LhIN2AXc5h7DIv7S0LHr+8GRZ1yQ5OdHd0YtwfiAAnoQiJ1K/AymjmG5xHGBXkqroiqOI+10TxNwjRcOI7Yu+fDOSQvIIxOg/XvZu12r0nAnos8BrnQ9eIiUEzCSv6jYw57KZ7VTyneYurT8tbQroz8W01RrKO9pifV9qqf1VxFTQ+zzFALJ03N1r8/RncnmhWWsXcP/v5eKoC0zKegbw="
        - secure: "HJzPWWk5EIovMU0Qf+jWLZ4VcUyJXnMDVM6sFITxENFNu+jHkCxWF2PYcuWJ2a3Md7Q1Me0TmdXT/ncfsvLlJGoA5h2B6yt7CwhZzxLqDkBrtELBd9WAgncKprDxmPNS5R+it8fAxqxf+Z1a9qT0JBZUbK1WdvxAPTxGQsXuo/FowcDdhVBWIaNHsZumWguXK0Q9taDqZd5q7Z3zJl06dhozwCn50t04j7LKHTaXqlTBh9v26NJ0ChUJ09JphqdRrK+zXnCKC+FcxqWWVRxNh00pH433Dzbnb4WvprV9rCNN+zfj7cA3aTkBBNhH2lPpGwdClhbN73uBzIfi2oSfAOs3gpXYYzYqAjW8OGAvYhp0ClvmGGPsXyA44yoVogr2NC+50KiNGJlZi/VtQxjCSC6OYWpBkbX0CEwZ5MQNLPFACplQN9Q5fzABmewC0AjMHgIzD7wzPID0ZAiBAFNDagTMdmla4koFGTr+git6bG9t58OQ+ieNJAao270VBmTDSST0kP1jEdizWPnr2UmyLz4p763sZk/AT5IgMXGAuLF+Vfpym/9j8k4iH1uMFIMgAFl4h1cXn4S/gsL7NLmI292mMRbLATv4227YUdg6cesGtFPjbqIMvenXKdf6G5hhoUEVJzgxWpgFi0cNM3l5qdxM5qQtOUJSyfDMrw4WB2o="
        - PATH=~/.roswell/bin:$PATH
        - ROSWELL_INSTALL_DIR=$HOME/.roswell

addons:
    apt:
        packages:
            - sshpass
cache:
    directories:
        - $HOME/.roswell

after_success:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh