language: common-lisp
sudo: false

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

cache:
    directories:
        - $HOME/.roswell

script:
  - ros -s prove -e '(or (prove:run :travis-test-test) (uiop:quit -1))'

env:
    global:
        - secure: "vnOrHnk1skckzieDIudoPP9GytRMuQc798EO+UIW4b9mt32VjKDSUCmDS9XlYoZkeVb3zjqcdncDzzBVE/HBwxlJkk9YQoDB7wl6fJWHqQcUDislEsirvGGIg9liy+zWUDiA67AV9hQyh9QPF9GXkzTYMxKTf8zWu81xSi1T59kCa5KGAmfxGbJUJGexfTr/v8Eg1UvOWf5lpQ9QEQYvITtZzQvVeRU+8Cfc3aYcsykYyewdC4+ZJu03F2itICY6fa9hCw3URCrWq9IinzQDLpUQ0BffkQAL0qnSSNhmrXaULGNbf70B5bqaFqYM7A8zQKOvn5DVFm4YCKPiwUtgwXg7DTu2hUCkNKb4EOewLaq18PNv9czl9DOR+4+ux9iPXUyWWqlBjVPNIFEjvo7S76vUi6jkBKmM6Wb2Nqc46+0dB0ct47AtKjlRli3f4ajnODnqdLGal9e/0cNyBBuy5hLJFVPlNhbhK3Id1zd0EJP1ua0aBhtwY5hp1C2fk+va2QcXGwX/4gWtyGe7go4MZsLlZ5nsiTNLePhLDXTFaxiOb/3MTHh9OIdlTmVltx0zYKEBwy1g89aYHFd7vFI8AoVsIodW6YBa3nSFNwBeFXJY0RtgmKjwmO1A0Y1Mn9ssZNcwRP7DNB0XlWCbF2tZjHvliDV2CZ/Hg5KFO8qa+xM="
        - secure: "XhBDhgZrbMIyc7BVoPb2s0dVywKObtTyUSLtDFaeG1QAHcrB8OtHi9F3eiR63RW7X9UYuG0UbDXKXsGs1/EdHolyqy6xojML1qYLrLbPnkfUundMbpzB4937lONUuXa/HtzLsKMh84XuUWm9Gc7K5WAyNQwpCiADp4OBbyc0PLPdudujz/QoB+W/rVaKFPN5ir6IxB9s7iF7RifsuZeYpMnKAzE4NSQSJ5X/J0aPeRRxn6sdEVQ66BUQys0EufV5LV4vvnee2bjWFNZ0ZYkHVPs9pur/+pIrOu2Nrm3Dd5BFnBEy+eC4/g621Kmc3bnyq3uPodYjzDF+8SJWS7HfhKy9iSG3gQCfXhEoxjHN0CvJpHYVVXwahEFHGu5kZuTkzGFhOKlsRKw3oui7Yf6SU/WKEsXXVEWkmnlzfgoPI7rfMPqhZKXyqXzM3xAAyQ9WwX6ohk5ze8fq6nVVGGjbixlUTZ3ntdTWjzSyJoXhkmZPG1/CyEZaVC9dCL0BYybxcdriOWZeJtjgbYnpYvDqG87zC05nYVp0KdiEGGfR/IzfZHWfKj3mvkOnz9Mqz9zMoahDfK3ZCcIKldSaYli0xGkUFAdBTxEUsMCIyrmNHLl8wf4qKL9oyExyTX0GU9BPwp8JBDXpyl3onIn/KHV4q+Tb3rURq9aqa5Fm9bvdzLQ="
        - secure: "bSQ66Ou/zSBAuqhvyBT+S/yel+QSDFyFbsflMK0Yx/vOqk5DeT8CL+7/VOgQfKgRPSI/CgVMc8lm6qGHfGRp45OshH6IEAMFEl3urUHGXwH+KPyxHHUjx47FMjRYr+cfha4LRIpzUitedzmfau8M9v33GsS+uCnI46rduXRtkOHC3n+dQbNBuUGfmttST0vPD4Slz8JTi57zBV1pxQ5f5tnR2/oXZOVBcGmSYGDuGF+fI2xd1pHZa32jn/QPcZ+7VUTDGD2IOK4duBFVOlMYalyw5tsOAjf+kbsweOgBIEFt/uLJ+WlOQBPjZwqoWspzGJmUUn5KG/m0cWvprcEaRVW5XeIc3pZcERH/zi2aKBZjDo716L8MCgVgBMkXgKbNgRf/bbieZhXAnm+vp7cjRr2gUiDCmEAvV+dfi7eMm3/0mqa1Ip+aGAVz84xLfUil2ApFOmuyYD1dRJ53JhgPNJ1M2MUMXRwmqI/rMAidzkHtn17KDJzZPepi6Gv6viiEMRal5AnuwjgYJxaRF7ftNB0/tMd3BzF9EJDrZNIXEWJiEzG3BXSuXPT6UKI2rpixHM+Kv/o304GHpo5ZTwe7djdCZ8HrvlRdQB0v+KVl8nLMWELHTo4JPuV92nog0cLl1JF78vTwwn2i0cAGsG4BWRWby8M445MShtFJ6eKJLgQ="
        - secure: "F9SoJRHjQaKn5+0bqJGl73GajufZE+1Z/pIagIVqbu6W5TUR6Ibmf35YL0Ruatp0S2WiwAGGtRtdjiLvOPeDhxdwJ0hP5zFj2us374Oj4svX7I746yLBfqjSkvWp3sVfFf+fb8RBTM6IURUeAaI2k5hQzOKCyR7pnFuWfBvVSoCYT/1SXg3GLLviN08y/3ryzVNMkY1ZFSQg+ulrV4Mj2xo5fL6BplBp0w3aFNGktHsbSbwmmLQrZzfY7FDysakczk28G5tV1GPQWeSYzTzSPKwpqjc1pvX3Qt6wZEsTMqMbqacf39VkFBR5eIoRnCbcyiMDNeZYsZd0IFrJ+CqdJaqDggUY9xC5FVXjP53nmMpiHbIiUub03y2cBJb7yuk5ZEru0HPieerEtfiBSq86LENWTTUzgPjcIBvR4mZ6Lv+LZ5MRl2zJWmPYuCX8/zCujskuyofqS0Egb8IG6SnMCUt/VRzGJfYDzHKP4qVSVgv0A0noaKI6PaebtdFz7yCNhS6mrjMUTLdoz3jLga3JPOoKjOEq1lt3qCf1x3ozq+8H55UaAZakEjcXqfcAWYQi57ceFr2CyQvPCBZKjrsqPlsICO/Y7FXiMjxZ27lDB4f5DYdHG5TYXiwr0sJ+fNhfxhPI+zfXhdVcp/gOu8mejbPLCkI6LwPrR7aKWEw4uhQ="
        - PATH=~/.roswell/bin:$PATH
        - ROSWELL_INSTALL_DIR=$HOME/.roswell

addons:
    apt:
        packages:
            - sshpass

after_success:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e ssh -o "StrictHostKeyChecking"=no $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh